version: '3'

services:
  redis:
    image: redis:7
    ports:
      - '6739:6739'

  express:
    image: orca-server-dev:latest
    ports:
      - '3001:3001'
    depends_on:
      - redis
    links:
      - redis
