services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: redis
    networks:
      - orca-testing

  orchestrator:
    image: orca-orchestrator
    container_name: orchestrator
    ports:
      - "4000:4000"
    env_file:
      - path: ./orchestrator/.env
        required: true
    environment:
      - REDIS_HOST=redis
    networks:
      - orca-testing
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./orchestrator/packages:/usr/packages
    depends_on:
      - postgres
      - redis

  echo-server:
    image: echo-server
    ports:
      - "9001:9001"
    container_name: echo-server
    networks:
      - orca-testing

  simple-server:
    image: simple-server
    ports:
      - "9000:9000"
    container_name: simple-server
    networks:
      - orca-testing

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      postgres_password: password
    networks:
      - orca-testing

networks:
  orca-testing:
    external: true
    name: orca-testing
