services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: redis-queue
    networks:
      - orca-testing

  web-server:
    image: orca-orchestrator
    ports:
      - "4000:4000"
    container_name: orchestrator
    environment:
      - REDIS_HOST=redis-queue
    networks:
      - orca-testing

  echo-server:
    image: echo-server
    ports:
      - "9001:9001"
    container_name: echo-server
    networks:
      - orca-testing

  simple-server:
    image: simple-server
    ports:
      - "9000:9000"
    container_name: simple-server
    networks:
      - orca-testing

networks:
  orca-testing:
    external: true
    name: orca-testing
