services:

  orchestrator:
    build: orchestrator/
    image: orca-orchestrator:latest
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      POSTGRES_URL: postgresql://postgres:password@postgres
    container_name: orchestrator
    volumes:
      - ./orchestrator/packages:/usr/packages
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - orca-testing
    restart: always

  echo-server:
    image: echo-server
    ports:
      - "9001:9001"
    container_name: echo-server
    networks:
      - orca-testing

  simple-server:
    image: simple-server
    ports:
      - "9000:9000"
    container_name: simple-server
    networks:
      - orca-testing

  postgres:
    image: postgres:10
    ports:
      - "5434:5432"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - orca-testing

volumes:
  db-data:
    external: true

networks:
  orca-testing:
    external: true
    name: orca-testing
