version: "3"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: grading-queue

  orchestrator:
    build: .
    image: orca-orchestrator:latest
    ports:
      - "4000:4000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_HOST=grading-queue
    container_name: orca-orchestrator
    command: yarn start
    restart: always
