from enum import Enum

class CodeFiles(Enum):
  """
  Enum that describes the different types of code files that
  may be processed for a grading job. Code files could either be:

  - Starter Code
  - Student Code
  - Professor Code (Tests)
  """
  
  starter_code = "$STARTER"
  student_code = "$STUDENT"
  professor_code = "$PROFESSOR"

def generate_save_dir_path(code_files_spec: CodeFiles,  secret: str) -> str:
  """
  Given a CodeFiles enum and a secret (generated by a GradingJob), generate a save directory 
  for one or more code files.
  """
  dir_path = f"{secret}_"
  if code_files_spec.starter_code:
    return dir_path + "starter"
  elif code_files_spec.student_code:
    return dir_path + "student"
  else:
    return dir_path + "professor"