services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    container_name: redis-queue
    networks:
      - orca-testing

  simple-server:
    image: simple-server
    ports:
      - "9000:9000"
    stop_grace_period: "2s"
    container_name: simple-server
    networks:
      - orca-testing

  echo-server:
    image: echo-server
    ports:
      - "9001:9001"
    container_name: echo-server
    networks:
      - orca-testing

networks:
  orca-testing:
    external: true
    name: orca-testing
    driver: bridge
