name: "Development - CI Testing for Code Quality"

on: [push]

jobs:
  grading_vm:
    name: "Grading VM Tests"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: grading-vm
    strategy:
      matrix:
        python-version: ["3.10.6"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: python -m orca_grader.tests.runner

  web_server:
    name: "Web Server Tests"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: orchestrator
    strategy:
      matrix:
        node-version: ["20.11.0"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"
      - name: "Install dependencies"
        run: yarn --frozen-lockfile
      - run: yarn workspaces run build 
      - run: yarn test
